#!/bin/sh

# Run as `sudo ./script/bootstrap`
DOCKER_VERSION="18.09.5-0ubuntu1"

# for installing node version manager
NODE_VERSION="v10.15.3"
NVM_VERSION="v0.34.0"

install_docker() {
    apt-get update \
        || echo "run with sudo, need to install apt packages" \
        && exit 1

    # incase any current installations exist
    apt-get remove docker docker-engine docker.io

    apt install -y --no-install-recommends \
    docker.io # ="$DOCKER_VERSION" todo get the package version correct

    systemctl start docker
    systemctl enable docker

    groupadd docker
    usermod -aG docker $USER

    echo "logout and back in to use docker without sudo"
}

install_nvm() {
    # install nvm
    curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/"$NVM_VERSION"/install.sh" | bash

    # need to be able to use nvm right away
    export NVM_DIR="$HOME/.nvm"

    if [ ! -s "$NVM_DIR/nvm.sh" ]; then
        echo "can't find nvm script, exiting"
        exit 1   
    fi

    \. "$NVM_DIR/nvm.sh"
    # built on 10.15.3
    nvm install "$NODE_VERSION"
    node --version
    npm --version
}

install_docker
install_nvm

echo "run `npm install` and then npm run develop to run locally"
