#!/bin/sh
# for deploying on AWS

# stop and remove any running containers
./script/down

docker build . -t mjdall_site

NGINX_LOG_DIR=$(pwd)/nginx_logs/

# start the ui container
docker run \
    --name mjdall_site \
    -v "$NGINX_LOG_DIR":/var/log/nginx/ \
    -p 80:80 \
    -d \
    mjdall_site
